let item=document.querySelector('.item1');
let item2=document.querySelector('.item2');
let item3=document.querySelector('.item3');
let item4=document.querySelector('.item4');
let recent_contests=document.querySelector('.recent-contests');
let weak_topics=document.querySelector('.weak_topics');
let strong_topics=document.querySelector('.strong_topics');
let recent_submissions=document.querySelector('.recent_submissions');
let statistics=document.querySelector('.statistics');
item.addEventListener('click',function(e){
    // console.log("hello");
    item.style.width="30vw";
    item.style.height="25vh";
    item2.style.width="24vw";
    item2.style.height="auto";
    item3.style.width="24vw";
    item3.style.height="auto";
    item4.style.width="24vw";
    item4.style.height="auto";
    recent_contests.remove();
    weak_topics.classList.remove('hidden');
    statistics.classList.add('hidden');
    recent_submissions.classList.add('hidden');
    strong_topics.classList.add('hidden');
    // insert_weak_topics();
    e.preventDefault();
});
item2.addEventListener('click',function(e){
    // console.log("aur bhai kya haal chaal");
    item2.style.width="30vw";
    item2.style.height="25vh";
    item.style.width="24vw";
    item.style.height="auto";
    item3.style.width="24vw";
    item3.style.height="auto";
    item4.style.width="24vw";
    item4.style.height="auto";
    
    recent_contests.remove();
    strong_topics.classList.remove('hidden');
    statistics.classList.add('hidden');
    recent_submissions.classList.add('hidden');
    weak_topics.classList.add('hidden');
    // insert_weak_topics();
    e.preventDefault();
});
item3.addEventListener('click',function(e){
    // console.log("aur bhai kya haal chaal");
    item3.style.width="30vw";
    item3.style.height="25vh";
    item.style.width="24vw";
    item.style.height="auto";
    item2.style.width="24vw";
    item2.style.height="auto";
    item4.style.width="24vw";
    item4.style.height="auto";
    recent_contests.remove();
    recent_submissions.classList.remove('hidden');
    statistics.classList.add('hidden');
    weak_topics.classList.add('hidden');
    strong_topics.classList.add('hidden');
    // insert_weak_topics();
    e.preventDefault();
});
item4.addEventListener('click',function(e){
    // console.log("aur bhai kya haal chaal");
    item4.style.width="30vw";
    item4.style.height="25vh";
    item.style.width="24vw";
    item.style.height="auto";
    item3.style.width="24vw";
    item3.style.height="auto";
    item2.style.width="24vw";
    item2.style.height="auto";
    recent_contests.remove();
    statistics.classList.remove('hidden');
    weak_topics.classList.add('hidden');
    recent_submissions.classList.add('hidden');
    strong_topics.classList.add('hidden');
    // insert_weak_topics();
    e.preventDefault();
});
